site_name: Documentación de DiagramaHub
site_description: Documentación oficial de DiagramaHub
site_author: DiagramaHub Team

theme:
  name: material
  language: es
  features:
    - navigation.tabs # Pestañas en la navegación
    - navigation.indexes # Hace clickeables las secciones
    - navigation.top # Botón de "volver arriba"
    - content.code.copy # Botón para copiar código

  # Configuración del modo Claro/Oscuro dinámico
  palette:
    # Modo Claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Modo Oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

# Selector de idiomas
extra:
  alternate:
    - name: Español
      link: /es/
      lang: es
    - name: English
      link: /en/
      lang: en

# Configuración de los menús
nav:
  - Español:
      - Inicio: es/index.md
      - Guía de Instalación: es/instalacion.md
      - Notas de Versión:
          - es/release-notes/index.md
          - 0.5.10: es/release-notes/0.5.10.md
          - 0.5.9: es/release-notes/0.5.9.md
          - 0.5.8: es/release-notes/0.5.8.md
          - 0.5.7: es/release-notes/0.5.7.md
          - 0.5.6: es/release-notes/0.5.6.md
          - 0.5.5: es/release-notes/0.5.5.md
          - 0.5.4: es/release-notes/0.5.4.md
          - 0.5.3: es/release-notes/0.5.3.md
          - 0.5.2: es/release-notes/0.5.2.md
          - 0.5.1: es/release-notes/0.5.1.md
          - 0.5.0: es/release-notes/0.5.0.md
          - 0.4.1: es/release-notes/0.4.1.md
          - 0.4.0: es/release-notes/0.4.0.md
          - 0.3.1: es/release-notes/0.3.1.md
          - 0.3.0: es/release-notes/0.3.0.md
          - 0.2.1: es/release-notes/0.2.1.md
          - 0.2.0: es/release-notes/0.2.0.md
          - 0.1.0: es/release-notes/0.1.0.md
  - English:
      - Home: en/index.md
      - Installation: en/installation.md
      - Release Notes:
          - en/release-notes/index.md
          - 0.5.10: en/release-notes/0.5.10.md
          - 0.5.9: en/release-notes/0.5.9.md
          - 0.5.8: en/release-notes/0.5.8.md
          - 0.5.7: en/release-notes/0.5.7.md
          - 0.5.6: en/release-notes/0.5.6.md
          - 0.5.5: en/release-notes/0.5.5.md
          - 0.5.4: en/release-notes/0.5.4.md
          - 0.5.3: en/release-notes/0.5.3.md
          - 0.5.2: en/release-notes/0.5.2.md
          - 0.5.1: en/release-notes/0.5.1.md
          - 0.5.0: en/release-notes/0.5.0.md
          - 0.4.1: en/release-notes/0.4.1.md
          - 0.4.0: en/release-notes/0.4.0.md
          - 0.3.1: en/release-notes/0.3.1.md
          - 0.3.0: en/release-notes/0.3.0.md
          - 0.2.1: en/release-notes/0.2.1.md
          - 0.2.0: en/release-notes/0.2.0.md
          - 0.1.0: en/release-notes/0.1.0.md

# Funcionalidades adicionales
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
